version: '3.8'
services:
  blue-print-api:
    image: blueprint-api:latest
    container_name: blueprint-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
