name: Publish Docker Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar          

      - uses: actions/upload-artifact@v3
        with:
          name: application-SNAPSHOT.jar
          path: ./build/libs/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./build/libs/

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
#       - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: application-SNAPSHOT.jar
          path: ./build/libs/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set env
        run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: bebrabig/blueprint:${{ env.DATE }}
