name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test
      - name: Build Docker image
        run: |
          docker build . -t my-image-name
      # The following steps are optional and are used to log in to DockerHub and push the image.
      - name: Log in to DockerHub
        run: echo "1715855zZ" | docker login -u bebrabig --password-stdin
      - name: Push Docker image
        run: docker push my-image-name